"""
Helix Health Group: Clinical Platform API (Python / FastAPI)
=============================================================
This service powers Part 1 of the demo and the AI Config feature.

Part 1 - helix-auto-scribe feature flag:
  A flag-change listener on the LaunchDarkly SDK fires the instant the flag is
  toggled in the dashboard. We relay that change to the browser over
  Server-Sent Events (SSE), so the UI shows or hides the Auto-Scribe panel in
  well under a second - no polling, no page reload.

AI Config - helix-clinical-ai (answers generated by Anthropic Claude):
  The model name and system prompt come from LaunchDarkly, not from this code.
  One context attribute, "department", routes each request to a variation:
      ED mode     : fast ICD-10 + CPT coding from an ED encounter
      OB mode     : thorough obstetric coding
      Parent mode : warm newborn guidance for parents ("my baby at 2am")

Run:
  pip install -r requirements.txt
  python main.py
"""

import os
import json
import asyncio
import re
from typing import AsyncGenerator

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse, JSONResponse
from dotenv import load_dotenv

import ldclient
from ldclient import Config, Context
from ldai.client import LDAIClient, AIConfig
from ldai.tracker import TokenUsage

import anthropic

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
# Load .env from parent directory (project root)
load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", ".env"), override=True)

# ---------------------------------------------------------------------------
# LaunchDarkly initialisation
# Replace "LD_SERVER_SDK_KEY" with your Test environment server-side SDK key
# if you are not using the .env file.
# ---------------------------------------------------------------------------
ldclient.set_config(Config(os.environ["LD_SERVER_SDK_KEY"]))
ld = ldclient.get()
ai_client = LDAIClient(ld)

# ---------------------------------------------------------------------------
# Anthropic client
# Replace "ANTHROPIC_API_KEY" with your key if not using .env.
# ---------------------------------------------------------------------------
anthropic_client = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

# ---------------------------------------------------------------------------
# App
# ---------------------------------------------------------------------------
app = FastAPI(title="Helix Health Group: Clinical Platform API")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------------------------------------------------------------------
# Part 1: SSE flag-change listener
#
# The LD SDK fires _on_flag_change() in a background thread whenever the
# helix-auto-scribe flag value changes for our system context.  We push
# that event onto an asyncio.Queue so every connected SSE client gets it
# immediately, no polling, no page reload required.
# ---------------------------------------------------------------------------
_sse_queues: list[asyncio.Queue] = []

# Handle to the uvicorn/asyncio event loop, captured when the first SSE client
# connects.  The LD SDK fires the change listeners on its own background thread,
# which has no event loop of its own, so it needs this reference to hand work
# back to the main loop via call_soon_threadsafe.
_main_loop: "asyncio.AbstractEventLoop | None" = None

# A generic "system" context used only to register flag listeners.
# Real per-user evaluation happens in the targeting endpoints.
_SYSTEM_CTX = Context.builder("helix-system").build()
# A maternity-staff context so the Part 2 badge reflects whether maternity
# clinicians currently see the pathway (helix-maternity-pathway is a targeting flag).
_MATERNITY_CTX = Context.builder("helix-maternity-staff").set("department", "maternity").build()


# Each entry: (flag key, evaluation context, default, value -> display transform).
# The display value is what that part's status badge shows in the UI; it is
# streamed over SSE so every part page reflects its own flag live.
_WATCHED_FLAGS = [
    ("helix-auto-scribe",        _SYSTEM_CTX,    False, lambda v: bool(v)),
    ("helix-maternity-pathway",  _MATERNITY_CTX, False, lambda v: bool(v)),
    ("helix-bp-alert-threshold", _SYSTEM_CTX,    140,   lambda v: int(v) if isinstance(v, (int, float)) else 140),
    ("helix-parent-connect",     _SYSTEM_CTX,    True,  lambda v: bool(v)),
]

# Current display value of each watched flag, kept live by the listeners below.
_flag_state: dict = {}


def _push_flag(flag_key: str, value) -> None:
    """Record a flag's display value and push it to every connected SSE client."""
    _flag_state[flag_key] = value
    payload = json.dumps({"flag": flag_key, "value": value})
    # Runs on the LD SDK's background thread; hand work to the main loop.
    if _main_loop is None:
        return
    for q in _sse_queues:
        _main_loop.call_soon_threadsafe(q.put_nowait, payload)


def _make_listener(flag_key: str, transform):
    """Build an LD change listener that streams the flag's display value."""
    def _listener(event) -> None:
        _push_flag(flag_key, transform(event.new_value))
    return _listener


for _fk, _ctx, _default, _transform in _WATCHED_FLAGS:
    # Seed the initial display value, then register a live change listener.
    _flag_state[_fk] = _transform(ld.variation(_fk, _ctx, _default))
    ld.flag_tracker.add_flag_value_change_listener(_fk, _ctx, _make_listener(_fk, _transform))


# ---------------------------------------------------------------------------
# GET /events: Server-Sent Events stream
# ---------------------------------------------------------------------------
@app.get("/events")
async def sse_events():
    """
    Browser connects here once.  When helix-auto-scribe is toggled in the
    LaunchDarkly dashboard the UI updates instantly, with no reload needed.
    """
    global _main_loop
    _main_loop = asyncio.get_running_loop()

    queue: asyncio.Queue = asyncio.Queue()
    _sse_queues.append(queue)

    async def generate() -> AsyncGenerator[str, None]:
        # Send every watched flag's current state so each part page is in sync on connect.
        for _fk, _value in list(_flag_state.items()):
            yield f"data: {json.dumps({'flag': _fk, 'value': _value})}\n\n"

        try:
            while True:
                try:
                    payload = await asyncio.wait_for(queue.get(), timeout=30)
                    yield f"data: {payload}\n\n"
                except asyncio.TimeoutError:
                    # Keepalive comment: prevents proxy/browser from closing the stream
                    yield ": keepalive\n\n"
        finally:
            _sse_queues.remove(queue)

    return StreamingResponse(
        generate(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# ---------------------------------------------------------------------------
# POST /code-encounter: AI Auto-Scribe (Extra Credit: AI Config)
#
# Receives a clinical transcript and returns structured ICD-10 + CPT codes.
# The LD AI Config "helix-clinical-ai" controls:
#   • Which Claude model is used  (Haiku for ED speed, Sonnet for OB depth)
#   • The system prompt / instructions  (specialty-specific coding guidance)
# Switching department context → different AI Config variation fires.
# ---------------------------------------------------------------------------
@app.post("/code-encounter")
async def code_encounter(request: Request):
    """
    Body (JSON):
      transcript  : str, raw clinical encounter text
      userId      : str, provider identifier
      department  : str, "ed" | "ob"
      role        : str, "attending" | "resident" | "charge_nurse"

    The "department" attribute routes to the correct AI Config variation:
      department=ed  → HELIX-SCRIBE-ED  (Haiku, ED coding prompt)
      department=ob  → HELIX-SCRIBE-OB  (Sonnet, OB coding prompt)
    """
    body = await request.json()
    transcript = body.get("transcript", "")
    user_key = body.get("userId", "provider-default")
    department = body.get("department", "ed")

    # Build context: the "department" attribute is the targeting key in LD
    context = (
        Context.builder(user_key)
        .set("department", department)
        .set("role", body.get("role", "attending"))
        .build()
    )

    # Fetch AI Config from LaunchDarkly
    # Create "helix-clinical-ai" as an AI Config in the LD Agents section
    ai_config, tracker = ai_client.config("helix-clinical-ai", context, AIConfig(enabled=False))

    if not ai_config.enabled:
        return {"error": "AI coding feature is currently disabled", "codes": []}

    model_name = (ai_config.model.name if ai_config.model and ai_config.model.name
                  else "claude-haiku-4-5-20251001")
    system_prompt = next(
        (m.content for m in (ai_config.messages or []) if m.role == "system"),
        ("You are a clinical coding assistant. Extract ICD-10 and CPT codes "
         "from the encounter transcript. Return valid JSON only."),
    )

    try:
        response = anthropic_client.messages.create(
            model=model_name,
            max_tokens=1024,
            system=system_prompt,
            messages=[{
                "role": "user",
                "content": (
                    f"Clinical encounter transcript:\n\n{transcript}\n\n"
                    "Return a JSON object with these exact keys:\n"
                    "  diagnosis       : string (primary diagnosis)\n"
                    "  icd10_codes     : array of {code, description}\n"
                    "  cpt_codes       : array of {code, description}\n"
                    "  complexity      : string (low | moderate | high)\n"
                    "  coding_notes    : string (brief rationale)\n"
                    "Return JSON only. No markdown fences."
                ),
            }],
        )

        tracker.track_success()
        tracker.track_tokens(
            TokenUsage(
                total=response.usage.input_tokens + response.usage.output_tokens,
                input=response.usage.input_tokens,
                output=response.usage.output_tokens,
            )
        )

        content = response.content[0].text.strip()
        # Strip any accidental markdown fences Claude might add
        content = re.sub(r"^```json\s*", "", content)
        content = re.sub(r"\s*```$", "", content)
        result = json.loads(content)

        return {
            "success": True,
            "department": department,
            "model_used": model_name,
            "result": result,
            "tokens": {
                "input": response.usage.input_tokens,
                "output": response.usage.output_tokens,
            },
        }

    except Exception as exc:
        return {"success": False, "error": str(exc), "codes": []}


# ---------------------------------------------------------------------------
# POST /parent-connect: Newborn guidance AI ("my baby at 2am")
#
# Patient-facing endpoint.  Uses the same helix-clinical-ai AI Config but
# with a "maternity-parent" department context, which routes to the warm,
# empathetic Parent Connect variation (Claude Sonnet).
#
# Two layers can disable the AI: the helix-parent-connect boolean flag (the
# feature gate) and the helix-clinical-ai AI Config's own enable toggle. If
# either is off, the parent is routed to the 24/7 nurse line.
# ---------------------------------------------------------------------------
@app.post("/parent-connect")
async def parent_connect(request: Request):
    """
    Body (JSON):
      message  : str, parent's description of their newborn's symptoms
      userId   : str, patient/parent identifier
    """
    body = await request.json()
    message = body.get("message", "")
    user_key = body.get("userId", "parent-default")

    context = (
        Context.builder(user_key)
        .set("department", "maternity-parent")
        .set("patient_type", "postpartum")
        .build()
    )

    # Feature gate (boolean flag). The Patient Experience team can flip
    # helix-parent-connect OFF in LaunchDarkly to instantly route every parent to
    # the 24/7 nurse line -- independently of the helix-clinical-ai AI Config that
    # controls the model and prompt. Default True so the feature works before the
    # flag exists; if LD is unreachable the AI Config call below also fails safe.
    if not ld.variation("helix-parent-connect", context, True):
        return {
            "response": (
                "Our AI care assistant is turned off right now. "
                "Please call our 24/7 nurse line at 1-800-HELIX-RN for immediate guidance."
            ),
            "escalate": False,
            "model_used": None,
        }

    ai_config, tracker = ai_client.config("helix-clinical-ai", context, AIConfig(enabled=False))

    if not ai_config.enabled:
        return {
            "response": (
                "Our AI care assistant is temporarily unavailable. "
                "Please call our 24/7 nurse line at 1-800-HELIX-RN for immediate guidance."
            ),
            "escalate": False,
            "model_used": None,
        }

    model_name = (ai_config.model.name if ai_config.model and ai_config.model.name
                  else "claude-sonnet-4-5-20251001")
    system_prompt = next(
        (m.content for m in (ai_config.messages or []) if m.role == "system"),
        ("You are HELIX-PARENT, a compassionate care assistant for new parents. "
         "Provide evidence-based guidance in plain, reassuring language. "
         "Always recommend calling 911 or going to the ED for emergencies. "
         "Never diagnose. Guide parents on when to seek care."),
    )

    try:
        response = anthropic_client.messages.create(
            model=model_name,
            max_tokens=1024,
            system=system_prompt,
            messages=[{"role": "user", "content": message}],
        )

        tracker.track_success()
        tracker.track_tokens(
            TokenUsage(
                total=response.usage.input_tokens + response.usage.output_tokens,
                input=response.usage.input_tokens,
                output=response.usage.output_tokens,
            )
        )

        content = response.content[0].text
        # Escalation heuristic: detect when the assistant is recommending urgent or
        # emergency care so the UI can surface a prominent "call 911 / go to the ER"
        # banner. We match common phrasings the model uses, plus a word-boundary check
        # for the "ER" abbreviation so we do not false-match substrings like "fever".
        content_lc = content.lower()
        _emergency_phrases = (
            "911", "9-1-1",
            "emergency room", "emergency department", "emergency care",
            "emergency services", "emergency medical", "medical emergency",
            "go to the ed", "ed immediately", "nearest ed",
            "call an ambulance", "call for an ambulance",
            "seek emergency", "seek immediate", "immediate medical attention",
            "nearest emergency",
        )
        escalate = (
            any(p in content_lc for p in _emergency_phrases)
            or re.search(r"\b(?:to the|go to the|nearest|visit the|head to the)\s+er\b", content_lc) is not None
            or re.search(r"\ber\b\s+(?:immediately|right away|right now|now)\b", content_lc) is not None
        )

        return {
            "response": content,
            "escalate": escalate,
            "model_used": model_name,
        }

    except Exception as exc:
        return {"error": str(exc), "escalate": False}


# ---------------------------------------------------------------------------
# GET /health
# ---------------------------------------------------------------------------
@app.get("/health")
def health():
    return {
        "status": "ok",
        "sdk_initialized": ld.is_initialized(),
        "flag_state": _flag_state,
    }


# ---------------------------------------------------------------------------
# GET /client-config
# The browser's LaunchDarkly JavaScript (client-side) SDK needs the *client-side
# ID* to initialise. That ID is designed to be public: it is safe to expose to
# the browser. The server SDK key and the Anthropic key never leave the server.
# We read the ID from .env so .env stays the single source of truth and the ID
# stays out of git (do not hardcode or commit it).
# ---------------------------------------------------------------------------
@app.get("/client-config")
def client_config():
    return {"clientSideId": os.environ["LD_CLIENT_SIDE_ID"]}


# ---------------------------------------------------------------------------
# GET /sdk/evalx/{flag_key}
# Stand-in for the LaunchDarkly client-side flag endpoint, used ONLY by the
# Part 5 "Simulate LaunchDarkly unavailable" button: it always returns
# 503 Service Unavailable, so the browser's polling shows a clean, realistic
# outage in DevTools -> Network. Real flag evaluation happens against
# LaunchDarkly in the browser, never here.
# ---------------------------------------------------------------------------
@app.get("/sdk/evalx/{flag_key}")
def simulate_ld_unavailable(flag_key: str):
    return JSONResponse(
        status_code=503,
        content={"error": "Service Unavailable", "flag": flag_key,
                 "message": "Simulated LaunchDarkly outage"},
    )


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")
